# Generated by Django 6.0.1 on 2026-02-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationBiasSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('forecast_high_f', models.FloatField()),
                ('observed_high_f', models.FloatField()),
                ('error_f', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['station_id', 'date'], name='polls_stati_station_9f4a35_idx')],
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
